# This file was generated by GoReleaser. DO NOT EDIT.
cask "hexplore" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "724f45cede891df9a4cec17aec7e9fbf8d94fce7bb89bf1efdffe31b0759a7fc"
      url "https://github.com/juniorsaldanha/hexplore/releases/download/v#{version}/hexplore_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c571cd72437277268494ebbd19eac40900003c57e291445c63e866f27d39a3e4"
      url "https://github.com/juniorsaldanha/hexplore/releases/download/v#{version}/hexplore_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dd2e280a3c89459be97c167d42656dc05ccdcebaea7dd1fefe8bc0139b6e3a38"
      url "https://github.com/juniorsaldanha/hexplore/releases/download/v#{version}/hexplore_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e4edf0326cad82e4a299b0fc5955562e0355adf7613d3ff69176e9c2417a1e9c"
      url "https://github.com/juniorsaldanha/hexplore/releases/download/v#{version}/hexplore_linux_amd64.tar.gz"
    end
  end

  name "hexplore"
  desc "Read-only Bitcoin block explorer for your terminal"
  homepage "https://github.com/juniorsaldanha/hexplore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hexplore"

  # No zap stanza required
end
