# This file was generated by GoReleaser. DO NOT EDIT.
cask "hexplore" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "24729fbf859401cfa90c3df61d3dbf7e7845dcde42ffbe202da47386f84efb0b"
      url "https://github.com/juniorsaldanha/hexplore/releases/download/v#{version}/hexplore_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a72e5237eb1efab37f00fe9cef972ea947ac21e753e58bfb6bb344b293d77c9e"
      url "https://github.com/juniorsaldanha/hexplore/releases/download/v#{version}/hexplore_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eccab221636b1b07107438a086ebf31478857e25c0331e19ef2a471fdc019c6f"
      url "https://github.com/juniorsaldanha/hexplore/releases/download/v#{version}/hexplore_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31a77d9cfb97aa9c8d837131da742f58700316fedc793b97e33e974aec08f270"
      url "https://github.com/juniorsaldanha/hexplore/releases/download/v#{version}/hexplore_linux_amd64.tar.gz"
    end
  end

  name "hexplore"
  desc "Read-only Bitcoin block explorer for your terminal"
  homepage "https://github.com/juniorsaldanha/hexplore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hexplore"

  # No zap stanza required
end
